# Generated by Django 2.0.4 on 2018-05-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enjoy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe_comment',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
