# Generated by Django 2.0.4 on 2018-05-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enjoy', '0002_auto_20180515_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Not_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('ani_name', models.CharField(max_length=40)),
            ],
        ),
    ]
